version: '3.0'
services:
  refdb:
    image: gcr.io/bloo-cloud/bloo-refdb:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./bloo-refdb/:/var/lib/mysql"
  graph:
    image: gcr.io/bloo-cloud/bloo-graph:latest
    restart: always
    links:
      - refdb
    volumes:
      - "./bloo-graph/:/opt/bloograph"
    ports:
      - "4000:4000"
    environment:
      REF_DB_HOST: refdb
      REF_DB_USERNAME: bloo
      REF_DB_PASSWORD: WxQDjscW7gCrHgXy22JS5BaK6yR65SmYXzwmXUmdcUfpHZd98Nj2qW6WwBVwFGKh
      REF_DB_NAME: bloo
      JWT_SECRET: Y2JNaFBBOXZVYnFxOFJ6cm00S3ZkQk51U0Y1ZkFNTlhHUWM5ZjdOdXM4SnQ0OExER1RtUTlXSmFyUUpYYUpTYUpXZlRFcVdXd3JDNVZKU2R1RnFjMlZDYm1GZm5SZTJaVENyMnpjdGdHMkNBSGI0Y2F2dHByejVWNGtDajJDc3d2cjZoUnBERTI4d3I5dlE2clZtM1JNWm0zbVN4cFpCSFBkN1ZocGVjUmVQUlQ3VG5aZFZQVThVZG5ZZHc1ejZ0RjVocDRKYUdHMjdUdTRDUHhSNndMZngyenE5ekhMdFRBU213U3VSanFVZmNhUXE0RDl1NVJzSFpTamFjVkR6OQ==
      JWT_REFRESH_SECRET: eG1Kakg4VHp2YzdQZ3Q5RlJYTEUycnZ4SlkzTVRwQlhqQlBNU0hCTVVWRVFTU1d4RzZKQmJaTHRhelMyNXZlZWNIRVFoTnI4SGRMWVhSNDZzVTRHVFB1alZFY1pIOHU0aFF2RFAzeUZnald1VXp5ZnFOUGF4eGpxeEJ4VUhmeW10ZVROZXc5dWRYVnpibUZtVFFBWUhBQkoyS3Q0RmVNZVFyU3FOQ3NreHU1cnhhRUMyS0tKdUFyRFhCQmZCN3dWcG5OWEN3QmdNSGJRcnVLYjhxdnd0Z0pjS1ZuNndwdGZRVkd5eUprWDNKWVlTclRFOVNIUnFhRVc2TnJEY1lDTg==
